// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlzfdeasvsevsmjywmuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsemZkZWFzdnNldnNtanl3bXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDI4MDQsImV4cCI6MjA2MjExODgwNH0.eB0r56x3eweHnFaMa0_XfR0AK7nA0EaNaP5RamfS8vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);